//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowYourVote2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Politician
    {
        public Politician()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int PoliticianID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
